### PR TITLE
Allow usage with Mongoid 4 through 6

### PR DESCRIPTION
**Pull request by artfuldodger**

### CODE REVIEW

**Comment by ConradIrwin** [comment]
@artfuldodger does this actually work? Happy to merge it if so

**Comment by hiroshi** [comment]
Hi, at least it works with mongoid 5.2.0 for me.

This gem should be merged in mongoid itself I suppose.

**Comment by ConradIrwin** [comment]
It should, but when I talked to @durran and @mongodb security they dismissed it as "WONTFIX" (maybe I did a bad job of explaining why this is a problem...)

Will push a new version for mongoid 5.2.0

**Comment by mmun** [comment]
Works for us too. Thanks for the release!

**Pull request merged**
